/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anmeldung mit E-Mail/Passwort, liefert JWT (US-05) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Erfolgreiche Anmeldung */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description Ungültige Anmeldedaten */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Zu viele Login-Versuche (Rate Limit, 5/Minute pro Client-IP) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aktuell angemeldeten Benutzer abrufen (US-05) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Benutzerinformationen */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abmeldung (US-05) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Abgemeldet */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Frage stellen, quellenbelegte Antwort erhalten (US-01, US-02) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryRequest"];
                };
            };
            responses: {
                /** @description Antwort mit Quellen und Konfidenz */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QueryResponse"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Frage fehlt oder verletzt die Längengrenzen (3 bis 1000 Zeichen). */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
                /** @description Zu viele Fragen (Rate Limit, 10/Minute pro Konto). Anders als beim Login zählt hier das angemeldete Konto und nicht die Client-IP — der Endpoint ist authentifiziert, und im Pilot teilen sich die Nutzer eine NAT-Adresse (Docs/03_QualityAttributes.md, Security). Schutz vor Schleifen und Missbrauch, keine Kostenobergrenze. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Retrieval oder Antwortgenerierung nicht verfügbar (LLM- bzw. Embedding-Provider oder Datenbank). Kein fachliches Ergebnis, sondern ein Infrastrukturfehler — bewusst nicht als Unterdrückung getarnt (ADR-008). */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/answers/{answer_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Antwort bewerten (US-03) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `answer_id` aus der QueryResponse */
                    answer_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FeedbackRequest"];
                };
            };
            responses: {
                /** @description Feedback gespeichert */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Kategorie passt nicht zu helpful (vier Gründe für 👍, fünf für 👎 — US-03) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Antwort nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dokumente des eigenen Bereichs auflisten (US-04) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste der Dokumente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentList"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Keine Berechtigung (Rolle knowledge_owner erforderlich) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Dokument hochladen; gleicher Dateiname ersetzt das bestehende (US-04, T-15) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["DocumentUploadRequest"];
                };
            };
            responses: {
                /** @description Bestehendes Dokument gleichen Namens ersetzt — gleiche id, alte Chunks gelöscht, Neu-Indexierung läuft */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentResponse"];
                    };
                };
                /** @description Neues Dokument angelegt, Verarbeitung läuft */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentResponse"];
                    };
                };
                /** @description Unbekannter Bereich (MVP: nur der hartcodierte Pilot-Bereich) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Keine Berechtigung (Rolle knowledge_owner erforderlich) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Datei überschreitet das 10-MB-Limit */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Nicht unterstütztes Dateiformat (erlaubt: PDF, DOCX, Markdown) */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dokument abrufen inkl. Verarbeitungsstatus (US-04) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    document_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dokument mit aktuellem Status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentResponse"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Keine Berechtigung (Rolle knowledge_owner erforderlich) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Dokument nicht gefunden (auch bei fremdem Bereich) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Dokument löschen (US-04) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    document_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dokument gelöscht */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Keine Berechtigung (Rolle knowledge_owner erforderlich) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Dokument nicht gefunden (auch bei fremdem Bereich) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Laufzeit-Konfiguration lesen (US-11) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alle Konfigurationswerte */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigResponse"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Keine Berechtigung (Rolle admin erforderlich) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /**
         * Laufzeit-Konfiguration schreiben (US-11)
         * @description Ersetzt die übergebenen Schlüssel; nicht genannte bleiben unverändert. Die Werte wirken ohne Neustart (ADR-008). Nur eine Teilmenge der über GET gelieferten Schlüssel ist schreibbar (Konfidenz-Bänder und die Retrieval-Parameter aus ADR-007); ein nicht schreibbarer Schlüssel mit unverändertem Wert wird stillschweigend akzeptiert, mit geändertem Wert abgelehnt — das erlaubt es einem Client, die volle GET-Antwort unverändert zurückzuschicken.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfigUpdateRequest"];
                };
            };
            responses: {
                /** @description Konfiguration nach der Änderung */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigResponse"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Keine Berechtigung (Rolle admin erforderlich) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unbekannter Schlüssel, ungültiger Wert, oder eine echte Änderung an einem nicht schreibbaren Schlüssel */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness-Probe für den Docker-Healthcheck
         * @description Bewusst ohne Authentifizierung: der Healthcheck läuft im Container ohne Zugangsdaten. Gibt keinerlei Zustandsdetails preis.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service erreichbar */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "learner" | "knowledge_owner" | "admin";
        Error: {
            /** @description Menschenlesbare Fehlerbeschreibung */
            detail: string;
        };
        /** @description FastAPIs Schema-Validierung. Bewusst nicht `Error`: hier ist `detail` eine Liste von Einzelfehlern, kein String — ein Client, der beide gleich behandelt, liest den falschen Typ. */
        ValidationError: {
            detail: {
                /** @description Pfad zum beanstandeten Feld, z. B. ["body", "question"] */
                loc: (string | number)[];
                msg: string;
                type: string;
            }[];
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        TokenResponse: {
            access_token: string;
            /** @default bearer */
            token_type: string;
            role: components["schemas"]["Role"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
        };
        QueryRequest: {
            question: string;
            /**
             * Format: uuid
             * @description Fortsetzung einer bestehenden Sitzung; null startet eine neue
             */
            session_id?: string | null;
        };
        /** @description Antwort der Konfidenz-Pipeline (ADR-008). Bei `suppressed` steht in `message` die standardisierte Weiss-ich-nicht-Antwort, nie generierter Fliesstext; `citations` darf die nächstliegenden Quellen enthalten, damit die Frage präzisiert werden kann (ADR-008, Band «Niedrig»). */
        QueryResponse: {
            /** Format: uuid */
            session_id: string;
            /**
             * Format: uuid
             * @description Adressiert das Feedback (POST /api/answers/{answer_id}/feedback)
             */
            answer_id: string;
            /** @description true, wenn eine Stufe der Pipeline unterdrückt hat */
            suppressed: boolean;
            /**
             * @description Welche Stufe unterdrückt hat (ADR-008). Geschlossene Menge, damit das Frontend jeden Wert beschriften kann statt den technischen Schlüssel anzuzeigen. Die Reihenfolge der Werte ist die Reihenfolge der Stufen; unterdrückt hat immer die erste, die nicht passiert. Stufe 2 unterscheidet zwei Fälle, weil sie operativ Verschiedenes bedeuten: `citation_coverage` ist eine Schwellenfrage und über `min_citation_coverage` kalibrierbar, `citation_invalid` ist eine erfundene Referenz und damit ein Modellfehler, der unabhängig von jeder Schwelle unterdrückt. `confidence_band` heisst, der Komposit-Score liegt unter `confidence_threshold_medium` (T-23), `self_check` heisst, die LLM-Verifikation hat ungedeckte Aussagen gemeldet oder kein lesbares Urteil geliefert (T-25).
             * @enum {string|null}
             */
            suppression_reason?: "retrieval_gate" | "retrieval_confidence" | "generation_refused" | "generation_truncated" | "citation_coverage" | "citation_invalid" | "confidence_band" | "self_check" | "configuration_error" | null;
            /** @description Antworttext, oder die Weiss-ich-nicht-Meldung bei Unterdrückung */
            message?: string | null;
            /** @description Vorschlag zur Präzisierung der Frage (Requirements §71, US-02). Nur bei `suppressed`, und je Unterdrückungsgrund ein anderer Text: nach «Weiss ich nicht» soll der Hinweis zum nächsten sinnvollen Schritt führen, und der ist bei einer zu breiten Frage ein anderer als bei einer erfundenen Referenz. null bei einer ausgelieferten Antwort — dort gibt es nichts zu präzisieren. */
            refinement_hint?: string | null;
            citations: components["schemas"]["Citation"][];
            confidence?: components["schemas"]["ConfidenceInfo"] | null;
            /** @description Nur für Rolle admin gefüllt */
            debug?: components["schemas"]["DebugInfo"] | null;
        };
        /** @description Quellenbeleg auf Chunk-Ebene (US-01) */
        Citation: {
            /** Format: uuid */
            chunk_id: string;
            /** Format: uuid */
            document_id: string;
            filename: string;
            page?: number | null;
            excerpt: string;
            /** @description Fussnotennummer im Antworttext */
            index: number;
        };
        /** @description Komposit-Score und seine Bestandteile (ADR-008) */
        ConfidenceInfo: {
            /**
             * Format: float
             * @description Der angezeigte Komposit-Score (ADR-008, T-23): gewichtete Kombination aus `retrieval_score` und `citation_coverage`. Lief Stufe 2 nicht, ist er die Retrieval-Konfidenz allein — eine Antwort, die es nie gab, hat keine Belegquote, die in den Score eingehen könnte. Die Herleitung steht in `debug.formula_breakdown`.
             */
            score: number;
            /** Format: float */
            retrieval_score: number;
            /**
             * Format: float
             * @description Anteil der Antwort-Segmente mit gültigem Beleg (ADR-008, Stufe 2). 0.0 heisst auch «Stufe 2 ist nicht gelaufen» — eine vor der Generierung unterdrückte Antwort hat keine Segmente, die belegt sein könnten. Ob die Stufe lief, steht in `debug.stages`.
             */
            citation_coverage: number;
            /**
             * @description Das Band, in das `score` fällt (ADR-008, US-02): `hoch` ab `confidence_threshold_high`, `mittel` ab `confidence_threshold_medium`, darunter `niedrig`. `mittel` ist die Anzeige «Eingeschränkt belegt», `niedrig` liefert immer eine unterdrückte Antwort. Lief Stufe 2 nicht, beschreibt das Band die Retrieval-Konfidenz allein und damit die gefundenen Stellen, nicht eine beurteilte Antwort — das gilt für jede Unterdrückung vor der Citation-Prüfung, auch für `generation_refused` und `generation_truncated`, wo bereits generiert wurde.
             * @enum {string}
             */
            band: "hoch" | "mittel" | "niedrig";
        };
        ChunkDebugInfo: {
            filename: string;
            page?: number | null;
            heading?: string | null;
            /** Format: float */
            score: number;
            above_threshold: boolean;
            in_top_n: boolean;
            dense_rank: number;
            content: string;
        };
        /** @description Eine Stufe der Defense-in-Depth-Pipeline (ADR-008), in Ausführungsreihenfolge. Übersprungene Stufen bleiben in der Liste mit `ran: false` — dass eine Stufe nicht lief, ist die Aussage, nicht ihre Abwesenheit. */
        StageInfo: {
            /** @description Stabiler Schlüssel der Stufe, den die Admin-Ansicht zum Einordnen der LLM-Aufrufe benutzt: `retrieval_gate`, `retrieval_confidence`, `citation_coverage`, `confidence_band`, `self_check`. */
            id: string;
            name: string;
            ran: boolean;
            passed: boolean;
            value?: (number | string) | null;
            /** Format: float */
            threshold?: number | null;
            detail: string;
        };
        LLMCallInfo: {
            step: string;
            label: string;
            prompt: string;
            response: string;
        };
        RetrievalDetail: {
            /** Format: float */
            top_score: number;
            /** Format: float */
            mean_score: number;
            /** Format: float */
            evidence_density: number;
            /** Format: float */
            result: number;
            count: number;
        };
        /** @description Nachvollziehbarkeit der Pipeline für die Admin-Ansicht. Nicht Teil des fachlichen Vertrags — Felder können sich mit der Pipeline ändern. */
        DebugInfo: {
            chunks: components["schemas"]["ChunkDebugInfo"][];
            stages: components["schemas"]["StageInfo"][];
            llm_calls: components["schemas"]["LLMCallInfo"][];
            /** Format: float */
            similarity_threshold: number;
            /** Format: float */
            min_retrieval_confidence: number;
            /** Format: float */
            min_citation_coverage: number;
            /** @description Ob Stufe 3 gelaufen ist (ADR-008, T-25). false ist der Normalfall: die Stufe kostet einen zweiten LLM-Aufruf und wird nur ausgelöst, wenn der Komposit-Score im Grenzband zwischen `self_check_band_low` und `self_check_band_high` liegt. */
            self_check_ran: boolean;
            /** @description Das Urteil der Verifikation im Wortlaut des Modells, null wenn die Stufe nicht lief. Bewusst der Rohtext und keine Kennzahl: ADR-008 verwirft die LLM-Selbsteinschätzung als Mass, und was die Stufe entschieden hat, steht im `self_check`-Eintrag von `stages`. */
            self_check_verdict?: string | null;
            retrieval_detail: components["schemas"]["RetrievalDetail"];
            /** @description Die für diese Anfrage gelesenen `config`-Werte, inklusive der Schwellen von Stufen, die nicht gelaufen sind — wer kalibriert, braucht alle, nicht nur die ausgelösten. Enthält neben den Retrieval-Parametern die Bandgrenzen `confidence_threshold_high`, `confidence_threshold_medium` (T-23) sowie `self_check_band_low` und `self_check_band_high` (T-25). */
            params_used: {
                [key: string]: number | null;
            };
            dense_above_threshold: number;
            total_dense_retrieved: number;
            sparse_count: number;
            top_n_used: number;
            formula_breakdown: string;
        };
        /**
         * @description Grund der Bewertung (US-03). Die ersten vier gelten für `helpful: true`, die übrigen fünf für `helpful: false`.
         * @enum {string}
         */
        FeedbackCategory: "verstaendlich" | "vollstaendig" | "hilfreich_fuer_code" | "quelle_passt_gut" | "faktisch_falsch" | "unvollstaendig" | "veraltet" | "unverstaendlich" | "quelle_stimmt_nicht";
        /** @description Bewertung einer Antwort (US-03). Wird pseudonymisiert erfasst — die Tabelle `feedback` hält bewusst keinen Bezug zur Nutzerin. */
        FeedbackRequest: {
            /** @description 👍 = true, 👎 = false */
            helpful: boolean;
            category?: components["schemas"]["FeedbackCategory"] | null;
            /** @description Optionale Freitext-Ergänzung */
            comment?: string | null;
        };
        ConfigResponse: {
            /** @description Schlüssel-Wert-Paare aus der config-Tabelle; Werte immer als String */
            config: {
                [key: string]: string;
            };
        };
        ConfigUpdateRequest: {
            config: {
                [key: string]: string;
            };
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        /** @enum {string} */
        DocumentStatus: "pending" | "processing" | "available" | "failed";
        DocumentUploadRequest: {
            /**
             * Format: binary
             * @description Dokument (PDF, DOCX oder Markdown), max. 10 MB
             */
            file: string;
            /**
             * @description Bereich; im MVP hartcodierter Pilot-Bereich
             * @default default
             */
            area: string;
        };
        DocumentResponse: {
            /** Format: uuid */
            id: string;
            filename: string;
            status: components["schemas"]["DocumentStatus"];
            area: string;
            chunk_count: number;
            error_message?: string | null;
            /**
             * Format: date-time
             * @description Zeitpunkt des ersten Uploads; überlebt eine Ersetzung (T-15)
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Zeitpunkt des Uploads der aktuellen Fassung (T-15)
             */
            updated_at: string;
        };
        DocumentList: components["schemas"]["DocumentResponse"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
