/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anmeldung mit E-Mail/Passwort, liefert JWT (US-05) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Erfolgreiche Anmeldung */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description Ungültige Anmeldedaten */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Zu viele Login-Versuche (Rate Limit, 5/Minute pro Client-IP) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aktuell angemeldeten Benutzer abrufen (US-05) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Benutzerinformationen */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abmeldung (US-05) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Abgemeldet */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Frage stellen, quellenbelegte Antwort erhalten (US-01, US-02) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryRequest"];
                };
            };
            responses: {
                /** @description Antwort mit Quellen und Konfidenz */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QueryResponse"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Noch nicht implementiert (T-17). Der Endpoint existiert als Dummy, damit Vertrag und Implementierung deckungsgleich bleiben; er liefert bewusst keine erfundene Antwort. Entfällt mit der Implementierung. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/answers/{answer_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Antwort bewerten (US-03) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description `answer_id` aus der QueryResponse */
                    answer_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FeedbackRequest"];
                };
            };
            responses: {
                /** @description Feedback gespeichert */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Antwort nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Noch nicht implementiert (T-30) — siehe /api/query */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dokumente des eigenen Bereichs auflisten (US-04) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste der Dokumente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentList"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Keine Berechtigung (Rolle knowledge_owner erforderlich) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Dokument in den Lernkorpus hochladen (US-04) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["DocumentUploadRequest"];
                };
            };
            responses: {
                /** @description Upload angenommen, Verarbeitung läuft */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentResponse"];
                    };
                };
                /** @description Unbekannter Bereich (MVP: nur der hartcodierte Pilot-Bereich) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Keine Berechtigung (Rolle knowledge_owner erforderlich) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Datei überschreitet das 10-MB-Limit */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Nicht unterstütztes Dateiformat (erlaubt: PDF, DOCX, Markdown) */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dokument abrufen inkl. Verarbeitungsstatus (US-04) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    document_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dokument mit aktuellem Status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentResponse"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Keine Berechtigung (Rolle knowledge_owner erforderlich) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Dokument nicht gefunden (auch bei fremdem Bereich) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Dokument löschen (US-04) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    document_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dokument gelöscht */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Keine Berechtigung (Rolle knowledge_owner erforderlich) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Dokument nicht gefunden (auch bei fremdem Bereich) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Laufzeit-Konfiguration lesen (US-11) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alle Konfigurationswerte */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigResponse"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Keine Berechtigung (Rolle admin erforderlich) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Noch nicht implementiert (T-37) — siehe /api/query */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /**
         * Laufzeit-Konfiguration schreiben (US-11)
         * @description Ersetzt die übergebenen Schlüssel; nicht genannte bleiben unverändert. Die Werte wirken ohne Neustart (ADR-008).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfigUpdateRequest"];
                };
            };
            responses: {
                /** @description Konfiguration nach der Änderung */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigResponse"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Keine Berechtigung (Rolle admin erforderlich) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unbekannter Schlüssel oder ungültiger Wert */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Noch nicht implementiert (T-37) — siehe /api/query */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness-Probe für den Docker-Healthcheck
         * @description Bewusst ohne Authentifizierung: der Healthcheck läuft im Container ohne Zugangsdaten. Gibt keinerlei Zustandsdetails preis.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service erreichbar */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "learner" | "knowledge_owner" | "admin";
        Error: {
            /** @description Menschenlesbare Fehlerbeschreibung */
            detail: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        TokenResponse: {
            access_token: string;
            /** @default bearer */
            token_type: string;
            role: components["schemas"]["Role"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
        };
        QueryRequest: {
            question: string;
            /**
             * Format: uuid
             * @description Fortsetzung einer bestehenden Sitzung; null startet eine neue
             */
            session_id?: string | null;
        };
        /** @description Antwort der Konfidenz-Pipeline (ADR-008). Bei `suppressed` steht in `message` die Weiss-ich-nicht-Antwort und `citations` bleibt leer. */
        QueryResponse: {
            /** Format: uuid */
            session_id: string;
            /**
             * Format: uuid
             * @description Adressiert das Feedback (POST /api/answers/{answer_id}/feedback)
             */
            answer_id: string;
            /** @description true, wenn eine Stufe der Pipeline unterdrückt hat */
            suppressed: boolean;
            /** @description Welche Stufe unterdrückt hat (ADR-008) */
            suppression_reason?: string | null;
            /** @description Antworttext, oder die Weiss-ich-nicht-Meldung bei Unterdrückung */
            message?: string | null;
            /** @description Vorschlag zur Präzisierung der Frage */
            refinement_hint?: string | null;
            citations: components["schemas"]["Citation"][];
            confidence?: components["schemas"]["ConfidenceInfo"] | null;
            /** @description Nur für Rolle admin gefüllt */
            debug?: components["schemas"]["DebugInfo"] | null;
        };
        /** @description Quellenbeleg auf Chunk-Ebene (US-01) */
        Citation: {
            /** Format: uuid */
            chunk_id: string;
            /** Format: uuid */
            document_id: string;
            filename: string;
            page?: number | null;
            excerpt: string;
            /** @description Fussnotennummer im Antworttext */
            index: number;
        };
        /** @description Komposit-Score und seine Bestandteile (ADR-008) */
        ConfidenceInfo: {
            /** Format: float */
            score: number;
            /** Format: float */
            retrieval_score: number;
            /** Format: float */
            citation_coverage: number;
        };
        ChunkDebugInfo: {
            filename: string;
            page?: number | null;
            heading?: string | null;
            /** Format: float */
            score: number;
            above_threshold: boolean;
            in_top_n: boolean;
            dense_rank: number;
            content: string;
        };
        /** @description Eine Stufe der Defense-in-Depth-Pipeline (ADR-008) */
        StageInfo: {
            id: string;
            name: string;
            ran: boolean;
            passed: boolean;
            value?: (number | string) | null;
            /** Format: float */
            threshold?: number | null;
            detail: string;
        };
        LLMCallInfo: {
            step: string;
            label: string;
            prompt: string;
            response: string;
        };
        RetrievalDetail: {
            /** Format: float */
            top_score: number;
            /** Format: float */
            mean_score: number;
            /** Format: float */
            evidence_density: number;
            /** Format: float */
            result: number;
            count: number;
        };
        /** @description Nachvollziehbarkeit der Pipeline für die Admin-Ansicht. Nicht Teil des fachlichen Vertrags — Felder können sich mit der Pipeline ändern. */
        DebugInfo: {
            chunks: components["schemas"]["ChunkDebugInfo"][];
            stages: components["schemas"]["StageInfo"][];
            llm_calls: components["schemas"]["LLMCallInfo"][];
            /** Format: float */
            similarity_threshold: number;
            /** Format: float */
            min_retrieval_confidence: number;
            /** Format: float */
            min_citation_coverage: number;
            self_check_ran: boolean;
            self_check_verdict?: string | null;
            retrieval_detail: components["schemas"]["RetrievalDetail"];
            params_used: {
                [key: string]: number | null;
            };
            dense_above_threshold: number;
            total_dense_retrieved: number;
            sparse_count: number;
            top_n_used: number;
            formula_breakdown: string;
        };
        /**
         * @description Grund der Bewertung (US-03). Die ersten vier gelten für `helpful: true`, die übrigen fünf für `helpful: false`.
         * @enum {string}
         */
        FeedbackCategory: "verstaendlich" | "vollstaendig" | "hilfreich_fuer_code" | "quelle_passt_gut" | "faktisch_falsch" | "unvollstaendig" | "veraltet" | "unverstaendlich" | "quelle_stimmt_nicht";
        /** @description Bewertung einer Antwort (US-03). Wird pseudonymisiert erfasst — die Tabelle `feedback` hält bewusst keinen Bezug zur Nutzerin. */
        FeedbackRequest: {
            /** @description 👍 = true, 👎 = false */
            helpful: boolean;
            category?: components["schemas"]["FeedbackCategory"] | null;
            /** @description Optionale Freitext-Ergänzung */
            comment?: string | null;
        };
        ConfigResponse: {
            /** @description Schlüssel-Wert-Paare aus der config-Tabelle; Werte immer als String */
            config: {
                [key: string]: string;
            };
        };
        ConfigUpdateRequest: {
            config: {
                [key: string]: string;
            };
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        /** @enum {string} */
        DocumentStatus: "pending" | "processing" | "available" | "failed";
        DocumentUploadRequest: {
            /**
             * Format: binary
             * @description Dokument (PDF, DOCX oder Markdown), max. 10 MB
             */
            file: string;
            /**
             * @description Bereich; im MVP hartcodierter Pilot-Bereich
             * @default default
             */
            area: string;
        };
        DocumentResponse: {
            /** Format: uuid */
            id: string;
            filename: string;
            status: components["schemas"]["DocumentStatus"];
            area: string;
            chunk_count: number;
            error_message?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        DocumentList: components["schemas"]["DocumentResponse"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
