"""Add pgqueuer job queue schema (v0.26.x)

This migration is the exact equivalent of `pgq install` for pgqueuer 0.26.3
with default settings (no PGQUEUER_PREFIX, Durability.durable = all tables logged).

Generated from: QueryBuilderEnvironment().build_install_query()
  queue_table        = pgqueuer
  queue_table_log    = pgqueuer_log
  statistics_table   = pgqueuer_statistics
  schedules_table    = pgqueuer_schedules
  queue_status_type  = pgqueuer_status
  function           = fn_pgqueuer_changed
  trigger            = tg_pgqueuer_changed
  channel            = ch_pgqueuer

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-10
"""

from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TYPE pgqueuer_status AS ENUM (
            'queued', 'picked', 'successful', 'exception', 'canceled', 'deleted'
        )
    """)

    op.execute("""
        CREATE TABLE pgqueuer (
            id               SERIAL PRIMARY KEY,
            priority         INT NOT NULL,
            queue_manager_id UUID,
            created          TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
            updated          TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
            heartbeat        TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
            execute_after    TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
            status           pgqueuer_status NOT NULL,
            entrypoint       TEXT NOT NULL,
            dedupe_key       TEXT,
            payload          BYTEA,
            headers          JSONB
        )
    """)
    op.execute("""
        CREATE INDEX pgqueuer_priority_id_id1_idx
            ON pgqueuer (priority ASC, id DESC)
            INCLUDE (id)
            WHERE status = 'queued'
    """)
    op.execute("""
        CREATE INDEX pgqueuer_updated_id_id1_idx
            ON pgqueuer (updated ASC, id DESC)
            INCLUDE (id)
            WHERE status = 'picked'
    """)
    op.execute("""
        CREATE INDEX pgqueuer_queue_manager_id_idx
            ON pgqueuer (queue_manager_id)
            WHERE queue_manager_id IS NOT NULL
    """)
    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS pgqueuer_unique_dedupe_key
            ON pgqueuer (dedupe_key)
            WHERE (status IN ('queued', 'picked') AND dedupe_key IS NOT NULL)
    """)

    op.execute("""
        CREATE TABLE pgqueuer_log (
            id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created    TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
            job_id     BIGINT NOT NULL,
            status     pgqueuer_status NOT NULL,
            priority   INT NOT NULL,
            entrypoint TEXT NOT NULL,
            traceback  JSONB DEFAULT NULL,
            aggregated BOOLEAN DEFAULT FALSE
        )
    """)
    op.execute("""
        CREATE INDEX pgqueuer_log_not_aggregated
            ON pgqueuer_log ((1))
            WHERE NOT aggregated
    """)
    op.execute("CREATE INDEX pgqueuer_log_created ON pgqueuer_log (created)")
    op.execute("CREATE INDEX pgqueuer_log_status  ON pgqueuer_log (status)")
    op.execute("""
        CREATE INDEX pgqueuer_log_job_id_status
            ON pgqueuer_log (job_id, created DESC)
    """)

    op.execute("""
        CREATE TABLE pgqueuer_statistics (
            id         SERIAL PRIMARY KEY,
            created    TIMESTAMP WITH TIME ZONE NOT NULL
                           DEFAULT DATE_TRUNC('sec', NOW() AT TIME ZONE 'UTC'),
            count      BIGINT NOT NULL,
            priority   INT NOT NULL,
            status     pgqueuer_status NOT NULL,
            entrypoint TEXT NOT NULL
        )
    """)
    op.execute("""
        CREATE UNIQUE INDEX pgqueuer_statistics_unique_count
            ON pgqueuer_statistics (
                priority,
                DATE_TRUNC('sec', created AT TIME ZONE 'UTC'),
                status,
                entrypoint
            )
    """)

    op.execute("""
        CREATE TABLE pgqueuer_schedules (
            id         SERIAL PRIMARY KEY,
            expression TEXT NOT NULL,
            entrypoint TEXT NOT NULL,
            heartbeat  TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
            created    TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
            updated    TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
            next_run   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
            last_run   TIMESTAMP WITH TIME ZONE,
            status     pgqueuer_status DEFAULT 'queued',
            UNIQUE (expression, entrypoint)
        )
    """)

    op.execute("""
        CREATE FUNCTION fn_pgqueuer_changed() RETURNS TRIGGER AS $$
        DECLARE
            to_emit BOOLEAN := false;
        BEGIN
            IF TG_OP = 'UPDATE' AND OLD IS DISTINCT FROM NEW THEN
                to_emit := true;
            ELSIF TG_OP = 'DELETE' THEN
                to_emit := true;
            ELSIF TG_OP = 'INSERT' THEN
                to_emit := true;
            ELSIF TG_OP = 'TRUNCATE' THEN
                to_emit := true;
            END IF;

            IF to_emit THEN
                PERFORM pg_notify(
                    'ch_pgqueuer',
                    json_build_object(
                        'channel',   'ch_pgqueuer',
                        'operation', lower(TG_OP),
                        'sent_at',   NOW(),
                        'table',     TG_TABLE_NAME,
                        'type',      'table_changed_event'
                    )::text
                );
            END IF;

            IF TG_OP IN ('INSERT', 'UPDATE') THEN
                RETURN NEW;
            ELSIF TG_OP = 'DELETE' THEN
                RETURN OLD;
            ELSE
                RETURN NULL;
            END IF;
        END;
        $$ LANGUAGE plpgsql
    """)

    op.execute("""
        CREATE TRIGGER tg_pgqueuer_changed
        AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON pgqueuer
        EXECUTE FUNCTION fn_pgqueuer_changed()
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER   IF EXISTS tg_pgqueuer_changed   ON pgqueuer")
    op.execute("DROP FUNCTION  IF EXISTS fn_pgqueuer_changed")
    op.execute("DROP TABLE     IF EXISTS pgqueuer_schedules")
    op.execute("DROP TABLE     IF EXISTS pgqueuer_statistics")
    op.execute("DROP TABLE     IF EXISTS pgqueuer_log")
    op.execute("DROP TABLE     IF EXISTS pgqueuer")
    op.execute("DROP TYPE      IF EXISTS pgqueuer_status")
